name: echo

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: echo stuff
      run: echo "$GITHUB_REF_NAME"
    - name: echo more stuff
      run: echo "${{github.ref_name}}"
    - name: echo even more stuff
      run: echo "${{github.ref}}"
 
