name: Test

env:
  CI: true
  DEBUG: pw:api

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: bahmutov/npm-install@v1
      - name: run features
        run: npm run test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-result-report
          path: reports/report.html
      - name: Copy reports
        run: |
          ls -al reports/
          mkdir public
          cp -a reports/. public/
          rm public/.gitignore
          ls -al public/
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set timestamp
        shell: bash
        run: echo "::set-output name=timestamp::$(date +'%s')"
        id: set_timestamp
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          destination_dir: ${{ steps.extract_branch.outputs.branch }}/${{ steps.set_timestamp.outputs.timestamp }}
          enable_jekyll: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_email: 'github-actions[bot]@users.noreply.github.com'
          user_name: 'github-actions[bot]'
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            Test report published @ <https://braddenver.github.io/cucumber-playwright-pages/${{ steps.extract_branch.outputs.branch }}/${{ steps.set_timestamp.outputs.timestamp }}/report.html>
